# Getting Started with PyTorch Tensors

This notebook covers the basics of creating tensors in PyTorch, checking for GPU support, and using different tensor initialization methods.

In [1]:
import torch
print(torch.__version__)

2.7.0


## 📌 Check PyTorch Version and GPU Availability

This cell imports PyTorch and checks whether a CUDA-enabled GPU is available for computations.

- `torch.__version__`: Shows the installed PyTorch version.
- `torch.cuda.is_available()`: Checks for GPU availability.
- `torch.cuda.get_device_name(0)`: Prints the GPU name if available.

In [16]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating Tensors in PyTorch

## 🔸 torch.empty()

Creates a tensor without initializing its values (they may be random garbage from memory). It's useful for performance optimization when you'll overwrite values later.

In [18]:
a = torch.empty(2,3)

## 🔍 Tensor Type

All tensors in PyTorch are instances of the `torch.Tensor` class.

In [ ]:
# Shows the type, which is <class 'torch.Tensor'>
type(a)

torch.Tensor

## 🔸 torch.zeros()

Creates a tensor filled with **zeros** of the specified shape.


In [19]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## 🔸 torch.ones()

Creates a tensor filled with **ones**.

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## 🔸 torch.rand()

Returns a tensor filled with random numbers sampled from a **uniform distribution** over `[0, 1)`.


In [20]:
# using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## 🔁 Random Values Without Seed

Calling `torch.rand()` multiple times without setting a seed generates different values each time.


In [9]:
# Without using seed
torch.rand(2,3)

tensor([[0.6467, 0.0892, 0.4105],
        [0.0370, 0.9593, 0.5894]])

## 🎯 torch.manual_seed(seed)

Sets the seed for random number generation to make results reproducible. Using the same seed ensures the same random values are generated.


In [21]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

## 🔸 torch.tensor()

Creates a tensor directly from a Python list or nested list.


In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

## 🔸 torch.arange(start, end, step)

Returns a 1D tensor with values from `start` to `end` (excluding `end`) with a given `step`.

In [ ]:
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


## 🔸 torch.linspace(start, end, steps)

Returns a 1D tensor with `steps` number of values evenly spaced between `start` and `end`.


In [29]:
# Using linspace
print("using linspace ->", torch.linspace(0, 10, 10))


using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


## 🔸 torch.eye(n)

Creates a 2D identity matrix of size `n x n`, with ones on the diagonal and zeros elsewhere.


In [30]:
# Using eye
print("using eye ->", torch.eye(5))


using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


## 🔸 torch.full(size, fill_value)

Creates a tensor of the specified size and fills it with the given value.

Example: `torch.full((3, 3), 5)` creates a 3x3 tensor of all fives.


In [ ]:
# using full
print("using full ->", torch.full((3, 3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# 📐 Tensor Shapes

You can inspect the shape of a tensor and create new tensors with the same shape using utility functions like `empty_like`, `zeros_like`, etc.


In [31]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

## 🔍 Inspect Tensor Shape

You can check the shape of a tensor using `.shape`.

In [33]:
x.shape

torch.Size([2, 3])

## 🔁 Create Tensors With the Same Shape

The following functions create new tensors with the **same shape as `x`**:
- `torch.empty_like(x)`
- `torch.zeros_like(x)`
- `torch.ones_like(x)`
- `torch.rand_like(x, dtype=...)` (can specify data type)


In [34]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [36]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# 🧬 Tensor Data Types

Every tensor in PyTorch has a data type (`dtype`). You can inspect or explicitly assign data types when creating tensors.

Use `.dtype` to check the data type of a tensor.

In [38]:
# find data type
x.dtype

torch.int64

## 🛠️ Assign a Data Type

You can specify the `dtype` explicitly while creating a tensor.


In [40]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [41]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## 🔄 Convert Tensor to a New Data Type

Use the `.to(dtype)` method to convert an existing tensor to a different data type.


In [42]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])