In [2]:
import torch
print(torch.__version__)

2.7.0


# Mathematical Operations in PyTorch

This section demonstrates how to perform various mathematical operations using PyTorch, including scalar operations, element-wise operations, reductions, matrix operations, comparisons, and special functions.


## 1. Scalar Operations

These operations apply a scalar value to every element in the tensor.


In [3]:
x = torch.rand(2, 2)
x

tensor([[0.7474, 0.7660],
        [0.2648, 0.1678]])

In [4]:
# Addition
x + 2

tensor([[2.7474, 2.7660],
        [2.2648, 2.1678]])

In [5]:
# Subtraction
x - 2

tensor([[-1.2526, -1.2340],
        [-1.7352, -1.8322]])

In [6]:
# Multiplication
x * 3

tensor([[2.2422, 2.2981],
        [0.7943, 0.5035]])

In [7]:
# Division
x / 3

tensor([[0.2491, 0.2553],
        [0.0883, 0.0559]])

In [13]:
# Integer division
(x * 100) // 3

tensor([[24., 25.],
        [ 8.,  5.]])

In [14]:
# Modulo
((x * 100) // 3) % 2

tensor([[0., 1.],
        [0., 1.]])

## 2. Element-wise Operations

Element-wise operations are performed between two tensors of the same shape.


In [15]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)


tensor([[0.1525, 0.6581, 0.5156],
        [0.8136, 0.7850, 0.0505]])
tensor([[0.3336, 0.7287, 0.2173],
        [0.4821, 0.5254, 0.9311]])


In [16]:
# Addition
a + b

tensor([[0.4860, 1.3868, 0.7329],
        [1.2957, 1.3105, 0.9817]])

In [17]:
# Subtraction
a - b

tensor([[-0.1811, -0.0706,  0.2982],
        [ 0.3315,  0.2596, -0.8806]])

In [18]:
# Multiplication
a * b

tensor([[0.0509, 0.4796, 0.1120],
        [0.3922, 0.4125, 0.0470]])

In [19]:
# Division
a / b

tensor([[0.4571, 0.9032, 2.3722],
        [1.6877, 1.4941, 0.0543]])

In [20]:
# Power
a ** b

tensor([[0.5340, 0.7372, 0.8659],
        [0.9053, 0.8806, 0.0621]])

In [21]:
# Modulo
a % b

tensor([[0.1525, 0.6581, 0.0809],
        [0.3315, 0.2596, 0.0505]])

In [22]:
c = torch.tensor([1, -2, 3, -4])


In [23]:
# Absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [24]:
# Negation
torch.neg(c)

tensor([-1,  2, -3,  4])

In [25]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [26]:
# Round
torch.round(d)

tensor([2., 2., 4., 4.])

In [27]:
# Ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [28]:
# Floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [29]:
# Clamp values between 2 and 3
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operations

These operations reduce a tensor to a single value or a smaller shape by aggregating values along a dimension.


In [46]:
e = torch.randint(size=(2, 3), low=1, high=10, dtype=torch.float32)
e

tensor([[2., 2., 3.],
        [8., 9., 3.]])

In [47]:
# Sum of all elements
torch.sum(e)

tensor(27.)

In [48]:
# Sum along columns (dim=0)
torch.sum(e, dim=0)

tensor([10., 11.,  6.])

In [49]:
# Sum along rows
torch.sum(e, dim=1)

tensor([ 7., 20.])

In [50]:
# Mean of all elements
torch.mean(e)


tensor(4.5000)

In [51]:
# Mean along columns
torch.mean(e, dim=0)


tensor([5.0000, 5.5000, 3.0000])

In [52]:
# Mean along rows
torch.mean(e, dim=1)

tensor([2.3333, 6.6667])

In [53]:
# Median
torch.median(e)


tensor(3.)

In [54]:
# Maximum
torch.max(e)


tensor(9.)

In [55]:
# Minimum
torch.min(e)


tensor(2.)

In [56]:
# Product of all elements
torch.prod(e)

tensor(2592.)

In [57]:
# Standard deviation
torch.std(e)


tensor(3.1464)

In [58]:
# Variance
torch.var(e)


tensor(9.9000)

In [59]:
# Index of max and min elements
torch.argmax(e), torch.argmin(e)

(tensor(4), tensor(0))

## 4. Matrix Operations

Matrix operations include matrix multiplication, dot product, transpose, inverse, and determinant. These are fundamental in linear algebra and deep learning.


In [60]:
f = torch.randint(size=(2, 3), low=1, high=10)
g = torch.randint(size=(3, 2), low=1, high=10)

print(f)
print(g)

tensor([[1, 5, 7],
        [2, 4, 6]])
tensor([[2, 7],
        [7, 3],
        [8, 7]])


In [61]:
# Matrix multiplication
torch.matmul(f, g)


tensor([[93, 71],
        [80, 68]])

In [62]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [63]:
# Dot product
torch.dot(vector1, vector2)


tensor(11)

In [64]:
# Transpose
torch.transpose(f, 0, 1)


tensor([[1, 2],
        [5, 4],
        [7, 6]])

In [66]:
h = torch.randint(size=(3, 3), low=1, high=10, dtype=torch.float32)
h


tensor([[1., 6., 3.],
        [3., 6., 6.],
        [5., 2., 3.]])

In [67]:
# Determinant
torch.det(h)

tensor(60.0000)

In [68]:
# Inverse
torch.inverse(h)


tensor([[ 0.1000, -0.2000,  0.3000],
        [ 0.3500, -0.2000,  0.0500],
        [-0.4000,  0.4667, -0.2000]])

## 5. Comparison Operations

Comparison operations return boolean tensors by comparing elements of tensors. Common comparisons include greater than, less than, equal to, and not equal to.


In [69]:
i = torch.randint(size=(2, 3), low=1, high=10)
j = torch.randint(size=(2, 3), low=1, high=10)

print(i)
print(j)


tensor([[6, 9, 6],
        [7, 4, 5]])
tensor([[1, 3, 4],
        [9, 8, 9]])


In [70]:
# Greater than
i > j


tensor([[ True,  True,  True],
        [False, False, False]])

In [71]:
# Less than
i < j


tensor([[False, False, False],
        [ True,  True,  True]])

In [72]:
# Equal to
i == j


tensor([[False, False, False],
        [False, False, False]])

In [73]:
# Not equal to
i != j


tensor([[True, True, True],
        [True, True, True]])

In [74]:
# Greater than or equal to
i >= j


tensor([[ True,  True,  True],
        [False, False, False]])

In [75]:
# Less than or equal to
i <= j


tensor([[False, False, False],
        [ True,  True,  True]])

## 6. Special Functions

PyTorch provides several advanced mathematical functions, including logarithmic, exponential, square root, and common activation functions like sigmoid, softmax, and ReLU.


In [76]:
k = torch.randint(size=(2, 3), low=1, high=10, dtype=torch.float32)
k


tensor([[8., 3., 7.],
        [5., 5., 5.]])

In [77]:
# Natural logarithm
torch.log(k)


tensor([[2.0794, 1.0986, 1.9459],
        [1.6094, 1.6094, 1.6094]])

In [78]:
# Exponential
torch.exp(k)


tensor([[2980.9580,   20.0855, 1096.6332],
        [ 148.4132,  148.4132,  148.4132]])

In [79]:
# Square root
torch.sqrt(k)


tensor([[2.8284, 1.7321, 2.6458],
        [2.2361, 2.2361, 2.2361]])

In [80]:
# Sigmoid function
torch.sigmoid(k)


tensor([[0.9997, 0.9526, 0.9991],
        [0.9933, 0.9933, 0.9933]])

In [81]:
# Softmax function
torch.softmax(k, dim=0)


tensor([[0.9526, 0.1192, 0.8808],
        [0.0474, 0.8808, 0.1192]])

In [82]:
# ReLU function
torch.relu(k)


tensor([[8., 3., 7.],
        [5., 5., 5.]])

## 7. Inplace Operations

In-place operations directly modify the content of a tensor without creating a new one. These operations are memory-efficient but should be used with care, especially when working with tensors that require gradient tracking.

In PyTorch, in-place operations are usually marked with an underscore at the end of the method name (e.g., `add_()`, `relu_()`).


In [83]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)


tensor([[0.9912, 0.0533, 0.6946],
        [0.9900, 0.7926, 0.8401]])
tensor([[0.6410, 0.9529, 0.9904],
        [0.1010, 0.5023, 0.5961]])


In [84]:
# In-place addition: modifies m directly
m.add_(n)
m


tensor([[1.6322, 1.0062, 1.6850],
        [1.0910, 1.2949, 1.4361]])

In [85]:
# n remains unchanged
n


tensor([[0.6410, 0.9529, 0.9904],
        [0.1010, 0.5023, 0.5961]])

In [86]:
# relu returns a new tensor (not in-place)
torch.relu(m)


tensor([[1.6322, 1.0062, 1.6850],
        [1.0910, 1.2949, 1.4361]])

In [87]:
# In-place ReLU: modifies m directly
m.relu_()
m


tensor([[1.6322, 1.0062, 1.6850],
        [1.0910, 1.2949, 1.4361]])

## 8. Copying a Tensor

In PyTorch, assigning one tensor to another using `b = a` does **not** create a new copy. Instead, both variables point to the same memory location. Any modification to one will affect the other.

To create an actual copy, use `a.clone()` which returns a new tensor with the same data but a different memory address.


In [88]:
# Create a tensor 'a'
a = torch.rand(2, 3)
a


tensor([[0.3239, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [89]:
# Assign 'a' to 'b' (no new memory is allocated)
b = a
b


tensor([[0.3239, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [90]:
# Modifying 'a' also changes 'b' since they share memory
a[0][0] = 0
a


tensor([[0.0000, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [91]:
# 'b' reflects the change in 'a'
b


tensor([[0.0000, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [92]:
# Check memory locations
id(a), id(b)  # Same ID means same object in memory


(5041150224, 5041150224)

In [93]:
# Create a true copy of 'a' using clone
b = a.clone()
a


tensor([[0.0000, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [94]:
# 'b' now holds a separate copy of the data
b


tensor([[0.0000, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [95]:
# Modify 'a' again
a[0][0] = 10
a


tensor([[10.0000,  0.4366,  0.5905],
        [ 0.6740,  0.4838,  0.5456]])

In [96]:
# 'b' remains unchanged since it's now a separate copy
b


tensor([[0.0000, 0.4366, 0.5905],
        [0.6740, 0.4838, 0.5456]])

In [97]:
# Check memory locations again
id(a), id(b)  # Different IDs indicate different objects


(5041150224, 5041152240)